"""Check native-generated bytes with the actual server schemas/WAV validator.

No server connection, credentials, database mutation, or synthetic HTTP upload.
Usage: python firmware/common/tests/verify_backend_contract.py BUILD_DIRECTORY
"""
from email import policy
from email.parser import BytesParser
import json
from pathlib import Path
import sys
from types import SimpleNamespace

PROJECT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(PROJECT))

from app.audio import analyze_audio, validate_wav  # noqa: E402
from app.schemas import UploadMetadata  # noqa: E402


def main() -> None:
    directory = Path(sys.argv[1])
    request = json.loads((directory / "firmware-request.json").read_text())
    body = (directory / "firmware-multipart.bin").read_bytes()
    assert len(body) == request["content_length"]
    assert len(request["boundary"]) <= 70
    envelope = (
        f'MIME-Version: 1.0\r\nContent-Type: multipart/form-data; boundary={request["boundary"]}\r\n\r\n'
    ).encode() + body
    parts = list(BytesParser(policy=policy.default).parsebytes(envelope).iter_parts())
    assert len(parts) == 2
    assert [part.get_param("name", header="content-disposition") for part in parts] == ["metadata", "file"]
    meta = UploadMetadata.model_validate_json(parts[0].get_payload(decode=True))
    assert meta.captured_at.isoformat() == "2026-10-09T10:00:00.123000+00:00"
    assert meta.sequence == 0
    wav = directory / "firmware-fixture.wav"
    assert parts[1].get_payload(decode=True) == wav.read_bytes()
    settings = SimpleNamespace(max_upload_bytes=20_000_000, allowed_sample_rates=[16000, 32000, 44100, 48000], max_duration_seconds=60)
    info = validate_wav(wav, settings)
    assert info.sample_rate == 16000 and info.frame_count == 3 and info.data_bytes == 9
    statistics = analyze_audio(wav, info)
    assert statistics.quality_status == "clipped"  # Deliberate signed-extreme packing fixture.
    assert statistics.clipped_samples == 2
    print("PASS: native multipart metadata and PCM24 WAV accepted by existing backend validators")


if __name__ == "__main__":
    main()
