"""Durable local-day jobs, compatible daily results and processing revision order.

This is additive: original sound records and live-event evidence are untouched.
"""
import os
from alembic import op

revision = "0004_daily_summaries"
down_revision = "0003_legacy_audio_guard"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("""
    ALTER TABLE measurements ADD COLUMN result_order bigint;
    WITH ordered AS (
      SELECT m.id, row_number() OVER (ORDER BY
        COALESCE(e.created_at,m.received_at), m.is_reprocessing, m.id) AS ordinal
      FROM measurements m LEFT JOIN measurement_evaluations e ON e.measurement_id=m.id
    ) UPDATE measurements m SET result_order=o.ordinal FROM ordered o WHERE o.id=m.id;
    ALTER TABLE measurements ALTER COLUMN result_order SET NOT NULL;
    ALTER TABLE measurements ALTER COLUMN result_order ADD GENERATED BY DEFAULT AS IDENTITY;
    SELECT setval(pg_get_serial_sequence('measurements','result_order'),
                  COALESCE((SELECT max(result_order) FROM measurements),0)+1, false);
    CREATE INDEX ix_measurements_audio_result_order ON measurements(audio_chunk_id,result_order);
    CREATE TABLE daily_reports (
      id uuid PRIMARY KEY, location_id uuid NOT NULL REFERENCES locations(id) ON DELETE RESTRICT,
      reporting_date date NOT NULL, timezone varchar(100) NOT NULL,
      day_start_utc timestamptz NOT NULL, day_end_utc timestamptz NOT NULL,
      status varchar(20) NOT NULL DEFAULT 'queued', attempts integer NOT NULL DEFAULT 0,
      available_at timestamptz NOT NULL DEFAULT now(), lease_until timestamptz, lease_token uuid,
      error text, requested_at timestamptz NOT NULL DEFAULT now(), started_at timestamptz,
      completed_at timestamptz, source_as_of timestamptz, updated_at timestamptz NOT NULL DEFAULT now(),
      CONSTRAINT uq_daily_report_location_date UNIQUE(location_id,reporting_date),
      CONSTRAINT ck_daily_report_status CHECK(status IN ('queued','processing','completed','failed')),
      CONSTRAINT ck_daily_report_attempts CHECK(attempts>=0),
      CONSTRAINT ck_daily_report_day CHECK(day_end_utc>day_start_utc),
      CONSTRAINT ck_daily_report_lease CHECK(
        (status='processing' AND lease_until IS NOT NULL AND lease_token IS NOT NULL)
        OR (status<>'processing' AND lease_until IS NULL AND lease_token IS NULL))
    );
    CREATE INDEX ix_daily_report_claim ON daily_reports(status,available_at,lease_until);
    CREATE TABLE daily_summaries (
      id uuid PRIMARY KEY, report_id uuid NOT NULL REFERENCES daily_reports(id) ON DELETE CASCADE,
      location_id uuid NOT NULL REFERENCES locations(id) ON DELETE RESTRICT,
      reporting_date date NOT NULL, definition_key varchar(64) NOT NULL,
      definition jsonb NOT NULL, statistics jsonb NOT NULL, calculated_at timestamptz NOT NULL,
      CONSTRAINT uq_daily_summary_definition UNIQUE(location_id,reporting_date,definition_key)
    );
    CREATE INDEX ix_daily_summary_report ON daily_summaries(report_id);
    """)
    role = os.environ.get("APP_DB_USER", "noise_app")
    quoted_role = '"' + role.replace('"', '""') + '"'
    op.execute(f"GRANT USAGE, SELECT ON SEQUENCE measurements_result_order_seq TO {quoted_role}")
    op.execute(f"GRANT SELECT, INSERT, UPDATE ON daily_reports TO {quoted_role}")
    op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON daily_summaries TO {quoted_role}")


def downgrade():
    raise RuntimeError("Daily report evidence is forward-only; restore a verified backup")
